services:
  nginx-rtmp:
    build:
      context: ./nginx-rtmp
      dockerfile: Dockerfile
    container_name: nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
      - "127.0.0.1:8088:8088"
    volumes:
      - hls-temp:/tmp/hls
      - nginx-logs:/var/log/nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.hls.rule=Host(`live.mecwish.com`) && PathPrefix(`/hls`)
      - traefik.http.routers.hls.entrypoints=https
      - traefik.http.routers.hls.tls=true
      - traefik.http.routers.hls.tls.certresolver=letsencrypt
      - traefik.http.services.hls.loadbalancer.server.port=8088

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_HLS_URL=https://live.mecwish.com/hls/testkey.m3u8
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`live.mecwish.com`)
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000

volumes:
  hls-temp:
  nginx-logs:
